# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NOTIFICATIONCENTRE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NOTIFICATIONCENTRE

  target 'NOTIFICATIONCENTRETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NOTIFICATIONCENTREUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'IQKeyboardManagerSwift', '6.0.4'
end
